AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'trips Rest API to manage a Data Lake of trips links

  '
Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Environment:
      Variables:
        TABLE_NAME:
          Ref: tripsTable
        ENDPOINT_OVERRIDE: ''
Resources:
  CreateTripsRecordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://test-lambda-jeff/9e81b34d1416ddcddf2479320a407dda
      Handler: br.com.iwe.handler.CreateTripsRecord::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: tripsTable
      Events:
        CreateTripsRecord:
          Type: Api
          Properties:
            Path: /trips
            Method: post
  GettripsRecordsByPeriodFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://test-lambda-jeff/9e81b34d1416ddcddf2479320a407dda
      Handler: br.com.iwe.handler.GettripsRecordsByPeriod::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: tripsTable
      Events:
        GettripsRecordsByPeriod:
          Type: Api
          Properties:
            Path: /trips/{country}/findByPeriod
            Method: get
            RequestParameters:
            - method.request.querystring.starts
            - method.request.querystring.ends
  GetTripsRecordsByCityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://test-lambda-jeff/9e81b34d1416ddcddf2479320a407dda
      Handler: br.com.iwe.handler.GetTripsRecordsByCity::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: tripsTable
      Events:
        GetTripsRecordsByCity:
          Type: Api
          Properties:
            Path: /trips/{country}/findByCity
            Method: get
            RequestParameters:
            - method.request.querystring.city
  GettripsRecordsByIsConsumedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://test-lambda-jeff/9e81b34d1416ddcddf2479320a407dda
      Handler: br.com.iwe.handler.GettripsRecordsByIsConsumed::handleRequest
      Runtime: java8
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: tripsTable
      Events:
        GettripsRecordsByIsConsumed:
          Type: Api
          Properties:
            Path: /trips/{country}/findByIsConsumed
            Method: get
            RequestParameters:
            - method.request.querystring.isconsumed
  tripsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: trips
      AttributeDefinitions:
      - AttributeName: country
        AttributeType: S
      - AttributeName: dateTimeCreation
        AttributeType: S
      - AttributeName: city
        AttributeType: S
      - AttributeName: consumed
        AttributeType: S
      KeySchema:
      - AttributeName: country
        KeyType: HASH
      - AttributeName: city
        KeyType: RANGE
      LocalSecondaryIndexes:
      - IndexName: dateTimeCreationIndex
        KeySchema:
        - AttributeName: country
          KeyType: HASH
        - AttributeName: dateTimeCreation
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      - IndexName: consumedIndex
        KeySchema:
        - AttributeName: country
          KeyType: HASH
        - AttributeName: consumed
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
Outputs:
  CreateTripsRecordFunction:
    Description: CreateTripsRecord Lambda Function ARN
    Value:
      Fn::GetAtt:
      - CreateTripsRecordFunction
      - Arn
  GettripsRecordsByPeriodFunction:
    Description: GettripsRecordsByPeriod Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GettripsRecordsByPeriodFunction
      - Arn
  GetTripsRecordsByCityFunction:
    Description: GetTripsRecordsByCity Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GetTripsRecordsByCityFunction
      - Arn
  GettripsRecordsByIsConsumedFunction:
    Description: GettripsRecordsByIsConsumed Lambda Function ARN
    Value:
      Fn::GetAtt:
      - GettripsRecordsByIsConsumedFunction
      - Arn
